onboarding = false

[keys]
prefix = "ctrl+s"
previous_workspace = "prefix+shift+left"
next_workspace = "prefix+shift+right"

[ui]
show_agent_labels_on_pane_borders = true

[experimental]
pane_history = false

[theme]
name = "gruvbox"
auto_switch = false
