#!/usr/bin/env bun
/**
 * CiGate.ts — Wave 4 / Item #10 / ISC-11.
 *
 * CI-friendly gate that converts a PiVerdict JSON file into a markdown
 * blob suitable for `gh pr comment --body-file -`. Exit code mirrors the
 * verdict so CI can fail the job on real defects.
 *
 *   PASS, CONCERNS → exit 0 (non-blocking; comment is informational)
 *   FAIL, REFRAME  → exit 1 (blocking; comment surfaces the blockers)
 *
 * Accepts both schema_version 1 and 2 input — `SchemaMigrate.migrate()`
 * forward-migrates v1 verdicts on load.
 *
 * Usage:
 *   bun run CiGate.ts --verdict <path> [--out <path>]
 *
 * Typical CI shape:
 *   bun run InvokePi.ts --phase VERIFY --isa ISA.md --diff diff.patch --json > verdict.json
 *   bun run CiGate.ts --verdict verdict.json | gh pr comment <PR> --body-file -
 *   # exit 1 fails the CI job; exit 0 lets it proceed.
 */

import { writeFileSync } from 'fs';
import { parseArgs } from 'util';

import { loadAndMigrate } from './SchemaMigrate.ts';
import type { PiBlocker, PiSuggestion, PiVerdict, Verdict } from './Schema.ts';

const VERDICT_BADGE: Record<Verdict, string> = {
  PASS: 'PASS',
  CONCERNS: 'CONCERNS',
  FAIL: 'FAIL',
  REFRAME: 'REFRAME',
};

function renderBlocker(b: PiBlocker, idx: number): string {
  const lines: string[] = [];
  lines.push(`### ${idx}. [${b.severity.toUpperCase()}] ${b.summary}`);
  lines.push('');
  if (b.evidence && b.evidence.length) {
    lines.push(`**Evidence:** ${b.evidence.map((e) => `\`${e}\``).join(', ')}`);
    lines.push('');
  }
  if (b.detail_md && b.detail_md.trim()) {
    lines.push(b.detail_md.trim());
    lines.push('');
  }
  return lines.join('\n');
}

function renderSuggestion(s: PiSuggestion, idx: number): string {
  const lines: string[] = [];
  lines.push(`### ${idx}. ${s.summary}`);
  lines.push('');
  if (s.detail_md && s.detail_md.trim()) {
    lines.push(s.detail_md.trim());
    lines.push('');
  }
  return lines.join('\n');
}

/**
 * Pure renderer. Takes a validated PiVerdict and returns the markdown body
 * for a PR comment. Headers are stable so downstream consumers can scrape.
 */
export function renderCiComment(verdict: PiVerdict): string {
  const out: string[] = [];
  const badge = VERDICT_BADGE[verdict.verdict];
  out.push(`# PiPerspective — ${verdict.phase} — ${badge}`);
  out.push('');
  out.push(
    `**Model:** \`${verdict.raw_model_id}\` · **Generated:** ${verdict.generated_at} · **Schema:** v${verdict.schema_version}`
  );
  out.push('');
  if (verdict.telemetry) {
    const t = verdict.telemetry;
    const bits: string[] = [];
    if (typeof t.duration_ms === 'number') bits.push(`duration_ms=${t.duration_ms}`);
    if (typeof t.input_chars === 'number') bits.push(`input_chars=${t.input_chars}`);
    if (bits.length) {
      out.push(`**Telemetry:** ${bits.join(', ')}`);
      out.push('');
    }
  }
  if (verdict.summary_md && verdict.summary_md.trim()) {
    out.push(verdict.summary_md.trim());
    out.push('');
  }

  const blockers = verdict.blockers ?? [];
  if (blockers.length > 0) {
    out.push(`## Blockers (${blockers.length})`);
    out.push('');
    const rank: Record<string, number> = { critical: 0, major: 1, minor: 2 };
    const sorted = [...blockers].sort(
      (a, b) => (rank[a.severity] ?? 9) - (rank[b.severity] ?? 9)
    );
    sorted.forEach((b, i) => out.push(renderBlocker(b, i + 1)));
  } else {
    out.push('## Blockers');
    out.push('');
    out.push('_No blockers raised._');
    out.push('');
  }

  const suggestions = verdict.suggestions ?? [];
  if (suggestions.length > 0) {
    out.push(`## Suggestions (${suggestions.length})`);
    out.push('');
    suggestions.forEach((s, i) => out.push(renderSuggestion(s, i + 1)));
  }

  out.push('---');
  out.push('');
  out.push(
    '_Generated by PiPerspective `CiGate.ts`. Exit 0 on PASS/CONCERNS, 1 on FAIL/REFRAME._'
  );
  out.push('');
  return out.join('\n');
}

/**
 * Wave 4 / ISC-11: failing verdicts (FAIL, REFRAME) exit non-zero so CI
 * blocks the merge. Non-failing verdicts (PASS, CONCERNS) exit zero — the
 * comment is informational.
 */
export function exitCodeFor(verdict: Verdict): 0 | 1 {
  return verdict === 'FAIL' || verdict === 'REFRAME' ? 1 : 0;
}

// ---------------------------------------------------------------------------
// CLI
// ---------------------------------------------------------------------------
if (import.meta.main) {
  const { values } = parseArgs({
    args: process.argv.slice(2),
    options: {
      verdict: { type: 'string' },
      out: { type: 'string' },
      help: { type: 'boolean', short: 'h' },
    },
    strict: true,
  });

  if (values.help || !values.verdict) {
    console.log('Usage: bun run CiGate.ts --verdict <path> [--out <path>]');
    process.exit(values.help ? 0 : 2);
  }

  let verdict: PiVerdict;
  try {
    verdict = loadAndMigrate(values.verdict);
  } catch (e) {
    console.error((e as Error).message);
    process.exit(2);
  }

  const body = renderCiComment(verdict);
  if (values.out) {
    writeFileSync(values.out, body, 'utf8');
    console.error(`Wrote ${values.out}`);
  } else {
    process.stdout.write(body);
  }
  process.exit(exitCodeFor(verdict.verdict));
}
