#!/usr/bin/env bash
# Emit the six per-stage tick jobs as a config-declared dsh-cron block, with
# each stage's prompt rendered from the ONE shared preamble.
#
#   ./render-jobs.sh                     # print the dsh-cron block to stdout
#   ./render-jobs.sh --install [PATCH]    # write it into cordis.patch.yml,
#                                        # replacing any existing dsh-cron row
#
# Config-declared, not manual, and that is the point. Manual jobs are stored in
# ~/.dsh/storages/cron.json where an agent can delete them with cron_delete --
# the build plan's rule is "an agent must not be able to delete its own
# heartbeat". Measured 2026-09-04: manual jobs also kept firing as `manual` runs
# after cron_disable, so deletion was the only stop that held, and deleting them
# took three unrelated jobs with it. Config-declared jobs can only be changed by
# editing profile config, which is reviewable and survives a restart.
#
# The prompts are NEVER hand-copied. Six jobs sharing a hand-copied 20KB
# preamble drift into six subtly different contracts; that is why the preamble
# is one file with a {{STAGE}} hole in it.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo="${REPO_PATH:-$(cd "$here/.." && pwd)}"
tz="${TICK_TZ:-America/Los_Angeles}"
schedule="${TICK_CRON:-*/15 * * * *}"
timeout="${TICK_TIMEOUT:-1800}"

# Model route for every tick. dsh-cron (lib/agent-task.js) reads task.provider
# and task.model; an empty string falls back to the host agent-default-model.
# Pinned to MiniMax M3 on the DIRECT minimax provider (settings.yaml:74/80),
# which bills against the MiniMax subscription rather than OpenRouter's paid
# egress. An explicit provider requires an explicit model (agent-task.js).
provider="${TICK_PROVIDER:-minimax}"
model="${TICK_MODEL:-MiniMax-M3}"

# Emitted disabled. A fresh install must not start ticking against an empty or
# half-configured board; enable one stage, watch a tick, then the rest.
enabled="${TICK_ENABLED:-false}"

install=0
patch="${2:-$HOME/.dsh/profiles/web/cordis.patch.yml}"
[ "${1:-}" = "--install" ] && install=1

emit() {
printf '# GENERATED by dsh-board/render-jobs.sh -- do not hand-edit.\n'
printf '# Regenerate after ANY preamble.md change; the prompts are frozen copies.\n'
printf -- '- id: dsh-cron\n'
printf '  config:\n'
printf '    historyLimit: 200\n'
printf '    sessionGc: { enabled: true, graceMinutes: 60 }\n'
printf '    jobs:\n'

for stage in Spec Decompose Build Verify Review Merge; do
  lc="${stage,,}"
  case "$stage" in
  Spec) desc="validates specs, promotes to Decompose or blocks" ;;
  Decompose) desc="creates the lane/worktree and the task breakdown" ;;
  Build) desc="dispatches the build team into the card's worktree" ;;
  Verify) desc="runs check.sh and the spec acceptance commands in the worktree" ;;
  Review) desc="dispatches a read-only review team over the lane diff" ;;
  Merge) desc="waits for the human merge, then cleans the lane and archives" ;;
  esac

  printf -- '      - name: dotfiles-tick-%s\n' "$lc"
  printf '        description: "dotfiles board tick — %s column only: %s"\n' "$stage" "$desc"
  printf '        enabled: %s\n' "$enabled"
  printf '        schedule: { cron: "%s", timeZone: %s }\n' "$schedule" "$tz"
  printf '        policy: { overlap: skip, misfire: skip }\n'
  printf '        task:\n'
  printf '          kind: agent\n'
  printf '          provider: %s\n' "$provider"
  printf '          model: %s\n' "$model"
  printf '          cwd: %s\n' "$repo"
  printf '          timeoutSeconds: %s\n' "$timeout"
  printf '          prompt: |\n'
  # cwd is mandatory and explicit: a cron job with no cwd falls back to
  # process.cwd() (dsh-cron lib/agent-task.js), which is unregistered, and the
  # board silently becomes a newly invented ~/.dsh-boards/<user>/board.json
  # while every tool result reads like a successful write to the real board.
  "$here/render-preamble.sh" "$stage" | sed 's/^/            /'
done
}

if [ "$install" -eq 0 ]; then
  emit
  exit 0
fi

[ -f "$patch" ] || { printf 'no such patch file: %s\n' "$patch" >&2; exit 1; }

# Replace any existing `- id: dsh-cron` row wholesale rather than appending a
# second one: two rows with the same id is a mount-time failure, and under
# dsh-startup-guard that is a boot failure.
# The block reaches python as a FILE, never through the heredoc body and never
# through the environment. An unquoted heredoc runs command substitution, so a
# backtick anywhere in 128KB of prompt would be executed by the shell; the
# environment route avoids that but blows the argv/env limit at this size
# (E2BIG: "Argument list too long"). A temp file has neither failure mode.
blockfile="$(mktemp)"
trap 'rm -f "$blockfile"' EXIT
emit >"$blockfile"

python3 - "$patch" "$blockfile" <<'PYEOF'
import re, sys, shutil
path, blockpath = sys.argv[1], sys.argv[2]
block = open(blockpath, encoding='utf-8').read().rstrip('\n')
shutil.copyfile(path, path + '.bak')
text = open(path, encoding='utf-8').read()
# Preserve each job's CURRENT enabled state across a re-install. The block is
# always rendered with the shipped default (enabled: false) so a FRESH install
# arrives disabled per INSTALL step 8. But a re-install (e.g. after a preamble
# edit) must not silently re-disable a board an operator already enabled --
# that turned into a real outage 2026-09-04 when --install reset all six to
# false and the scheduler went dark. So carry the existing per-job flag over.
prev = dict(re.findall(
    r'^ {6}- name: (dotfiles-tick-\w+)\n(?:(?! {6}- ).*\n)*? {8}enabled: (true|false)',
    text, re.M))
def _restore(m):
    return m.group(1) + prev.get(m.group('name'), m.group('cur'))
block = re.sub(
    r'(^ {6}- name: (?P<name>dotfiles-tick-\w+)\n(?:(?! {6}- ).*\n)*? {8}enabled: )(?P<cur>true|false)',
    _restore, block, flags=re.M)
# Strip the previous generated block INCLUDING its banner comments. Matching
# only the `- id: dsh-cron` row left the two `# GENERATED` lines behind, so
# each install appended another pair and no two installs produced the same
# file. That destroys the property this generator exists for: a regenerate
# must be a no-op unless a source actually changed, or real drift becomes
# indistinguishable from install noise.
pat = re.compile(
    r'^(?:# GENERATED by dsh-board/render-jobs\.sh.*\n(?:#.*\n)*)?'
    r'- id: dsh-cron\n(?:(?!^- |^#).*\n)*',
    re.M,
)
text = pat.sub('', text)
if not text.endswith('\n'):
    text += '\n'
open(path, 'w', encoding='utf-8').write(text.rstrip('\n') + '\n\n' + block + '\n')
print('installed dsh-cron block into ' + path + ' (backup: ' + path + '.bak)')
PYEOF
