lastChangelogVersion: 15.7.3
symbolPreset: nerd
setupVersion: 1
theme: 
  {}
inspect_image: 
  enabled: true
modelRoles: 
  default: zai/glm-5.1
  plan: openai-codex/gpt-5.5
  slow: openai-codex/gpt-5.4
  smol: zai/glm-4.7-flash
  commit: zai/glm-4.7-flash
  vision: openai-codex/gpt-5.5
extensions: 
  []