/**
 * harness-gates — Pi adapter that bridges Pi tool-lifecycle events onto the
 * deterministic gate scripts generated by the harness-apply Claude skill.
 *
 * This file contains ZERO gate logic. Each tool_call/tool_result event is
 * mapped onto one or more `.claude/hooks/*.sh` scripts, which are spawned as
 * subprocesses. The script templates (authored by harness-apply) own the
 * rules; this file only translates Pi's event shape into the synthesized
 * stdin JSON the scripts expect.
 *
 * --- Synthesized stdin contract per script (the ONE coupling point) -------
 *
 *   Bash gates (PreToolUse, matcher Bash):
 *     block-bash-pattern.sh   reads { tool_input:{ command } }
 *     pre-git-checks.sh       reads { tool_input:{ command } }
 *     staged-static-check.sh  reads { tool_input:{ command } }
 *
 *   Path gates (PreToolUse, matcher Edit|Write|MultiEdit + Read):
 *     block-path-access.sh    reads { tool_name, tool_input:{ file_path } }
 *
 *   Result gates (PostToolUse, matcher Edit|Write|MultiEdit):
 *     format-on-edit.sh       reads { tool_input:{ file_path } }  (fail-open)
 *     validate-syntax.sh      reads { tool_input:{ file_path } }
 *     lint-on-edit.sh         reads { tool_input:{ file_path } }  (fail-open)
 *
 * Exit code 2 from any script -> block the tool call / mark result as error.
 * Non-empty Bash-gate stderr on a passing exit -> warning notification.
 * Scripts that don't exist on disk are skipped silently (script discovery is
 * opportunistic: any missing arm is treated as not configured).
 *
 * --- Script discovery -----------------------------------------------------
 *
 * Scripts are looked up in BOTH `~/.claude/hooks/` (global, machine-level) and
 * `<projectRoot>/.claude/hooks/` (project, repo-level). The project copy wins
 * when both define the same name. Only the scripts that actually exist are
 * invoked; the rest are treated as not configured for this project.
 */

import { spawn } from "node:child_process";
import { existsSync } from "node:fs";
import { homedir } from "node:os";
import { join, dirname, resolve } from "node:path";

// --- Project-root discovery ------------------------------------------------

/**
 * Walk up from `cwd` looking for the nearest `.git` entry (file or dir).
 * Returns the directory containing `.git`, or `cwd` as a fallback so the
 * adapter never crashes when the cwd isn't inside a git repo.
 */
export function findProjectRoot(cwd) {
	let dir = resolve(cwd || process.cwd());
	const stop = dirname(dir); // walk at most to filesystem root
	while (true) {
		if (existsSync(join(dir, ".git"))) return dir;
		if (dir === stop) return resolve(cwd || process.cwd());
		dir = dirname(dir);
	}
}

// --- Script runner ---------------------------------------------------------

/**
 * Spawn `scriptPath` with `CLAUDE_PROJECT_DIR=<root>` in its env and
 * `JSON.stringify(payload)` on stdin. Resolves with `{ code, stderr }`.
 * Never throws — script failures are reported through the result.
 */
export function runHook(scriptPath, payloadObj, projectRoot) {
	return new Promise((resolveResult) => {
		const child = spawn("/bin/bash", [scriptPath], {
			env: { ...process.env, CLAUDE_PROJECT_DIR: projectRoot },
			stdio: ["pipe", "pipe", "pipe"],
		});
		let stderr = "";
		child.stderr.on("data", (chunk) => {
			stderr += chunk.toString("utf8");
		});
		child.stdout.on("data", () => {
			// Most gate scripts write nothing on stdout; consume to avoid
			// backpressure. (stop-quality-check emits JSON to stdout — its
			// result is intentionally ignored here; we only care about code.)
		});
		child.on("error", (err) => {
			resolveResult({ code: 1, stderr: stderr + String(err) });
		});
		child.on("close", (code) => {
			resolveResult({ code: code ?? 0, stderr });
		});
		// Ignore EPIPE — fast-exiting scripts (no stdin reader) close the
		// pipe before our write completes. The script ran fine; we only
		// care about its exit code and stderr.
		child.stdin.on("error", () => {});
		child.stdin.end(JSON.stringify(payloadObj));
	});
}

// --- Script discovery ------------------------------------------------------

function scriptDirs(projectRoot) {
	// Global first, project last. discoverScripts does NOT break on first hit,
	// so a project-level script (evaluated later) overwrites a same-named global
	// one — project wins by filename, matching Claude Code's project-over-global.
	const dirs = [];
	const globalHooks = join(homedir(), ".claude", "hooks");
	if (existsSync(globalHooks)) dirs.push(globalHooks);
	const projectHooks = join(projectRoot, ".claude", "hooks");
	if (existsSync(projectHooks)) dirs.push(projectHooks);
	return dirs;
}

/**
 * For each requested script name, find the first existing path across
 * global → project hook dirs (project wins). Returns a Map<name, absPath>.
 * Missing scripts are simply absent from the map.
 */
export function discoverScripts(scriptNames, projectRoot) {
	const dirs = scriptDirs(projectRoot);
	const out = new Map();
	for (const name of scriptNames) {
		// dirs is [global, project]; do NOT break on the first hit — let a
		// later dir (project) overwrite an earlier one (global) so project
		// wins by filename, per _shared/harness-gap-handoff.md scope layering.
		for (const dir of dirs) {
			const candidate = join(dir, name);
			if (existsSync(candidate)) {
				out.set(name, candidate);
			}
		}
	}
	return out;
}

// --- Event -> script mapping -----------------------------------------------

const BASH_BLOCKING_SCRIPTS = [
	"block-bash-pattern.sh",
	"pre-git-checks.sh",
	"staged-static-check.sh",
];

const PATH_GATE_SCRIPT = "block-path-access.sh";

const RESULT_SCRIPTS = [
	"format-on-edit.sh", // fail-open
	"validate-syntax.sh",
	"lint-on-edit.sh", // fail-open
];

const FAIL_OPEN = new Set(["format-on-edit.sh", "lint-on-edit.sh"]);

/**
 * Run Bash gate scripts sequentially; the FIRST exit-2 wins. Non-blocking
 * stderr is reported through `onAdvisory` after all gates pass.
 */
export async function runBashGates(payload, projectRoot, onAdvisory) {
	const scripts = discoverScripts(BASH_BLOCKING_SCRIPTS, projectRoot);
	const advisories = [];
	for (const name of BASH_BLOCKING_SCRIPTS) {
		const scriptPath = scripts.get(name);
		if (!scriptPath) continue;
		const { code, stderr } = await runHook(scriptPath, payload, projectRoot);
		const trimmed = stderr.trim();
		if (code === 2)
			return {
				block: true,
				reason: trimmed || "blocked by harness-gate",
			};
		if (trimmed) advisories.push(trimmed);
	}
	if (advisories.length > 0) onAdvisory?.(advisories.join("\n"));
	return undefined;
}

/**
 * Run the path-access gate for a write/edit/read event.
 */
export async function runPathGate(toolName, filePath, projectRoot) {
	const scripts = discoverScripts([PATH_GATE_SCRIPT], projectRoot);
	const scriptPath = scripts.get(PATH_GATE_SCRIPT);
	if (!scriptPath) return undefined;
	const payload = { tool_name: toolName, tool_input: { file_path: filePath } };
	const { code, stderr } = await runHook(scriptPath, payload, projectRoot);
	if (code === 2)
		return { block: true, reason: stderr.trim() || "blocked by harness-gate" };
	return undefined;
}

/**
 * Run the post-tool result gates. Format-on-edit and lint-on-edit are
 * fail-open — their exit code is ignored and their stderr is surfaced as a
 * notification (NOT as isError, so the agent doesn't see "formatted X" as a
 * tool failure). validate-syntax is fail-closed — exit 2 flips isError=true.
 */
export async function runResultGates(filePath, projectRoot) {
	const scripts = discoverScripts(RESULT_SCRIPTS, projectRoot);
	const payload = { tool_input: { file_path: filePath } };
	const notifications = []; // fail-open stderr, informational only
	const errors = []; // fail-closed exit-2, flips isError
	for (const name of RESULT_SCRIPTS) {
		const scriptPath = scripts.get(name);
		if (!scriptPath) continue;
		const { code, stderr } = await runHook(scriptPath, payload, projectRoot);
		const trimmed = stderr.trim();
		if (FAIL_OPEN.has(name)) {
			if (trimmed) notifications.push(trimmed);
			continue;
		}
		if (code === 2) {
			errors.push(trimmed || "blocked by harness-gate");
			break;
		}
	}
	if (errors.length === 0 && notifications.length === 0) return undefined;
	const text = [...errors, ...notifications].join("\n");
	return {
		isError: errors.length > 0,
		content: [{ type: "text", text }],
	};
}

// --- Extension entry point -------------------------------------------------

export default function harnessGatesExtension(pi) {
	pi.on("tool_call", async (event, ctx) => {
		const projectRoot = findProjectRoot(ctx?.cwd);
		const toolName = event?.toolName;
		const input = event?.input || {};

		if (toolName === "bash") {
			const command = String(input.command || "");
			const notify = (message) => {
				if (ctx.hasUI) ctx.ui.notify(message, "warning");
				else console.warn(message);
			};
			return runBashGates({ tool_input: { command } }, projectRoot, notify);
		}

		if (toolName === "read") {
			const filePath = String(input.file_path || input.path || "");
			if (!filePath) return undefined;
			return runPathGate("Read", filePath, projectRoot);
		}

		if (toolName === "write" || toolName === "edit") {
			const filePath = String(input.file_path || input.path || "");
			if (!filePath) return undefined;
			const piToolName = toolName === "write" ? "Write" : "Edit";
			return runPathGate(piToolName, filePath, projectRoot);
		}

		return undefined;
	});

	pi.on("tool_result", async (event, ctx) => {
		const projectRoot = findProjectRoot(ctx?.cwd);
		const toolName = event?.toolName;
		if (toolName !== "write" && toolName !== "edit") return undefined;
		const input = event?.input || {};
		const filePath = String(input.file_path || input.path || "");
		if (!filePath) return undefined;
		return runResultGates(filePath, projectRoot);
	});
}
